#!/bin/bash
function gvt_fetch {
	CMD="go get"
	BASE="src/"
	if [ -d "vendor/" ]; then
		CMD="gvt fetch"
		BASE="vendor/"
	fi
	if [ ! -d "$BASE$1" ]; then
		echo "Fetching: $1"
		$CMD $1
	fi
}

gvt_fetch github.com/namsral/flag
gvt_fetch github.com/gorilla/mux

rm -f docker-proxy-acl
go build docker-proxy-acl.go
./docker-proxy-acl "$@"